export const sample_foods = [
  {
    id: 1,
    name: "Pizza Pepperoni",
    cookTime: "20-25",
    price: 600,
    favorite: false,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: 2,
    name: "Hamburger",
    cookTime: "15-20",
    price: 300,
    favorite: false,
    origins: ["Germany", "US"],
    stars: 4,
    imageUrl: "food-2.jpg",
    tags: ["FastFood", "Burger"],
  },
  {
    id: 3,
    name: "Mo:Mo",
    cookTime: "30-35",
    price: 200,
    favorite: false,
    origins: ["Nepal", "Tibet"],
    stars: 4.5,
    imageUrl: "food-3.jpg",
    tags: ["FastFood", "MoMo", "Lunch"],
  },
  {
    id: 4,
    name: "Chowmein",
    cookTime: "20-25",
    price: 180,
    favorite: false,
    origins: ["China"],
    stars: 3.5,
    imageUrl: "food-4.jpg",
    tags: ["FastFood", "Lunch"],
  },
  {
    id: 5,
    name: "Egg + Bread Toast",
    cookTime: "5-10",
    price: 150,
    favorite: false,
    stars: 4,
    imageUrl: "food-5.jpg",
    tags: ["Breakfast", "LightMeal"],
  },
  {
    id: 6,
    name: "Biryani",
    cookTime: "20-25",
    price: 200,
    favorite: false,
    origins: ["Persian"],
    stars: 3.5,
    imageUrl: "food-6.jpg",
    tags: ["FastFood", "Lunch"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 5 },
  { name: "Pizza", count: 1 },
  { name: "Lunch", count: 4 },
  { name: "Burger", count: 1 },
  { name: "Breakfast", count: 1 },
  { name: "LightMeal", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "Sanjeet Shrestha",
    email: "sanjeetshrestha@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];
